{
    "CallName":"EN: Names and Things",
   	"CallDescription": "",
	"FontName": "",
	"Data": [
	["65", "A", "America"],
	["66", "B", "Berlin"],
	["67", "C", "Canada"],
	["68", "D", "Denmark"],
	["69", "E", "Europe"],
	["70", "F", "France"],
	["71", "G", "Germany"],
	["72", "H", "Hungary"],
	["73", "I", "India"],
	["74", "J", "Jamaica"],
	["75", "K", "Korea"],
	["76", "L", "London"],
	["77", "M", "Maljorka"],
	["78", "N", "Norway"],
	["79", "O", "Oxford"],
	["80", "P", "Panama"],
	["81", "Q", "Quebec"],
	["82", "R", "Rome"],
	["83", "S", "Spain"],
	["84", "T", "Taiwan"],
	["85", "U", "Ukraine"],
	["86", "V", "Vienna"],
	["87", "W", "Washington"],
	["88", "X", "Xiamen"],
	["89", "Y", "York"],
	["90", "Z", "Zambia"],
	["97", "a", "alcohol"],
	["98", "b", "bank"],
	["99", "c", "cable"],
	["100", "d", "dream"],
	["101", "e", "echo"],
	["102", "f", "force"],
	["103", "g", "ground"],
	["104", "h", "hotel"],
	["105", "i", "ice"],
	["106", "j", "job"],
	["107", "k", "key"],
	["108", "l", "label"],
	["109", "m", "memory"],
	["110", "n", "noise"],
	["111", "o", "object"],
	["112", "p", "plant"],
	["113", "q", "queen"],
	["114", "r", "radio"],
	["115", "s", "salt"],
	["116", "t", "table"],
	["117", "u", "uniform"],
	["118", "v", "vertical"],
	["119", "w", "whiskey"],
	["120", "x", "xray"],
	["121", "y", "yellow"],
	["122", "z", "zulu"]
]}