//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JocysCom.Password.Generator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default: Easy To Remember")]
        public string PresetNameComboBox {
            get {
                return ((string)(this["PresetNameComboBox"]));
            }
            set {
                this["PresetNameComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EN: NATO")]
        public string CallNameComboBox {
            get {
                return ((string)(this["CallNameComboBox"]));
            }
            set {
                this["CallNameComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowOnlyOneCopy {
            get {
                return ((bool)(this["AllowOnlyOneCopy"]));
            }
            set {
                this["AllowOnlyOneCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minimized")]
        public string StartWithWindowsState {
            get {
                return ((string)(this["StartWithWindowsState"]));
            }
            set {
                this["StartWithWindowsState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinimizeToTray {
            get {
                return ((bool)(this["MinimizeToTray"]));
            }
            set {
                this["MinimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyOnGenerate {
            get {
                return ((bool)(this["CopyOnGenerate"]));
            }
            set {
                this["CopyOnGenerate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenPasswordListFileAfterSave {
            get {
                return ((bool)(this["OpenPasswordListFileAfterSave"]));
            }
            set {
                this["OpenPasswordListFileAfterSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateTimer {
            get {
                return ((bool)(this["GenerateTimer"]));
            }
            set {
                this["GenerateTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenerateOnCopy {
            get {
                return ((bool)(this["GenerateOnCopy"]));
            }
            set {
                this["GenerateOnCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveProgramSettingsOnExit {
            get {
                return ((bool)(this["SaveProgramSettingsOnExit"]));
            }
            set {
                this["SaveProgramSettingsOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneratePasswordOnStart {
            get {
                return ((bool)(this["GeneratePasswordOnStart"]));
            }
            set {
                this["GeneratePasswordOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeOnClose {
            get {
                return ((bool)(this["MinimizeOnClose"]));
            }
            set {
                this["MinimizeOnClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveProgramSettings {
            get {
                return ((bool)(this["SaveProgramSettings"]));
            }
            set {
                this["SaveProgramSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default: Easy To Remember")]
        public string FavPreset1ComboBox {
            get {
                return ((string)(this["FavPreset1ComboBox"]));
            }
            set {
                this["FavPreset1ComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default: Good")]
        public string FavPreset2ComboBox {
            get {
                return ((string)(this["FavPreset2ComboBox"]));
            }
            set {
                this["FavPreset2ComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hex: GUID - Default")]
        public string FavPreset3ComboBox {
            get {
                return ((string)(this["FavPreset3ComboBox"]));
            }
            set {
                this["FavPreset3ComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Easy")]
        public string FavPreset1TextBox {
            get {
                return ((string)(this["FavPreset1TextBox"]));
            }
            set {
                this["FavPreset1TextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hard")]
        public string FavPreset2TextBox {
            get {
                return ((string)(this["FavPreset2TextBox"]));
            }
            set {
                this["FavPreset2TextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Guid")]
        public string FavPreset3TextBox {
            get {
                return ((string)(this["FavPreset3TextBox"]));
            }
            set {
                this["FavPreset3TextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPasswordWhenStart {
            get {
                return ((bool)(this["CopyPasswordWhenStart"]));
            }
            set {
                this["CopyPasswordWhenStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checked")]
        public global::System.Windows.Forms.CheckState ShowMultiEditPanelToolStripButtonCheckState {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["ShowMultiEditPanelToolStripButtonCheckState"]));
            }
            set {
                this["ShowMultiEditPanelToolStripButtonCheckState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ContactsShowMultiEditPanelToolStripButtonChecked {
            get {
                return ((bool)(this["ContactsShowMultiEditPanelToolStripButtonChecked"]));
            }
            set {
                this["ContactsShowMultiEditPanelToolStripButtonChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AccountsShowMultiEditPanelToolStripButtonChecked {
            get {
                return ((bool)(this["AccountsShowMultiEditPanelToolStripButtonChecked"]));
            }
            set {
                this["AccountsShowMultiEditPanelToolStripButtonChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartWithWindows {
            get {
                return ((bool)(this["StartWithWindows"]));
            }
            set {
                this["StartWithWindows"] = value;
            }
        }
    }
}
