{
	"PresetName":"Default",
	"PresetDescription":"",
	"PresetRemarks":"",
    "PasswordLength":9,
    "UseNumbers":false,
    "UseUppercase":false,
    "UseLowercase":false,
    "UseSymbols":false,
    "UseExtra":false,
    "RatioNumbers":1,
    "RatioUppercase":4,
    "RatioLowercase":8,
    "RatioSymbols":1,
    "RatioExtra":1,
	"CharsNumbers":"",
	"CharsUppercase":"",
	"CharsLowercase":"",
	"CharsSymbols":"",
	"CharsExtra":"",
    "FilterRemember":false,
    "FilterKeyboard":false,
    "FilterEnforce":false,
    "FilterPhone":false,
    "FilterAscii":false,
    "FilterChars":false,
	"FilterCharsString":"O0QIl1",
	"ScriptEnabled": false,
	"ScriptLanguage": "JScript",
	"ScriptEntry": "Class1.Main",
	"ScriptCode": "",
	"RegexEnabled": false,
	"RegexPatternFind": "",
	"RegexPatternReplace": "",
	"RegexIgnoreCase": false
}
